// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJPvd-6iKG_4e5JZ-Wuu0I6hRpl-ZNxBA',
    appId: '1:114930691434:android:d297225a5b55813a3d4913',
    messagingSenderId: '114930691434',
    projectId: 'app-chat-dcae5',
    storageBucket: 'app-chat-dcae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmdHGo1nRAD4rw-_gjYofPhItNgtnT04E',
    appId: '1:114930691434:ios:c28337bd5257ee8c3d4913',
    messagingSenderId: '114930691434',
    projectId: 'app-chat-dcae5',
    storageBucket: 'app-chat-dcae5.appspot.com',
    androidClientId: '114930691434-nc5jhn6t7lcnn0uc9qop2tmetg1n5or1.apps.googleusercontent.com',
    iosClientId: '114930691434-53qlvn0eentd4gmn6ekg1kpjtoq78ncj.apps.googleusercontent.com',
    iosBundleId: 'com.example.appchat',
  );
}
